version: 2

docker_defaults: &docker_defaults
  docker:
    - image: circleci/node:8.11.3-stretch-browsers

jobs:
  build:
    <<: *docker_defaults
    steps:
      - checkout
      - run:
          name: wtf
          command: sudo apt-get install -y libudev-dev libusb-1.0-0
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: test node
          command: node test.js
      - run:
          name: test electron
          command: ./node_modules/.bin/electron test.js
