version: 2

jobs:
  build_linux:
    docker:
      - image: circleci/node:8.11.3-stretch-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: test node
          command: node test.js
      - run:
          name: test electron
          command: ./node_modules/.bin/electron test.js
  build_macos:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: test node
          command: node test.js
      - run:
          name: test electron
          command: ./node_modules/.bin/electron test.js

workflows:
  version: 2
  build:
    jobs:
      - build_linux
      - build_macos
